### ISSUE TITLE
Truncating last column and last row

### ISSUE THREAD

**Issue by dbeef** [septag/atlasc#2]
## Problem:

Given this 16x16 image in input:

![0](https://user-images.githubusercontent.com/13459304/76192150-664bc900-61e1-11ea-83e1-5b951dcc97db.png)

This 24x24 image is outputted:

![level_tiles](https://user-images.githubusercontent.com/13459304/76192198-88454b80-61e1-11ea-86ed-a9054e7b3426.png)

Truncating last column (blue) and last row (red).

How to reproduce:

`atlasc 0.png -o level_tiles`

## Rest of the story:

I was looking for a command line texture packer, with no graphical interface, with just the very exact options your tool exposes, and I am very satisfied. Easy to build (about time for everyone to finally switch to CMake), no dependencies outside of the codebase. Just fantastic.

That being said, I am afraid there's a bug.

My use case is packing a bunch of uniform, 16x16 tiles that I will use in my tile renderer.
I also utilize the mesh option, so to parse UVs and normalize them during game's runtime, and use outputted index buffer.

So I found out that using outputted UVs pixel bleeding occurs. As I investigated, UVs seemed to be OK (16x16), also no half-pixel correction was needed on my side.

I looked at the tilesheet outputted from atlasc and I was bewildered - every tile was 15x15 instead of 16x16 given in input.

My call was:

`atlasc *.png -o level_tiles -B 0 -P 0 -m -W 512 -H 512 -2`

Am I using atlasc wrong?

**Comment by dbeef** [comment]
In my trivial use case applying this correction by one:

![off_by_one](https://user-images.githubusercontent.com/13459304/76247170-68dd0b80-623f-11ea-9f03-699f8472a587.png)

Fixes the problem, but I imagine that for sprites of non uniform size such naive approach may not work.

**Comment by septag** [comment]
Sorry to get back to you late.  and thanks for your nice comments about this repo
I'll inspect the bug and get back to you soon.

**Comment by septag** [comment]
Actually, you are right!
sprite_rect is [0, 0, 15, 15] , which shouldn't be the case obviously. I added a single unit to the rectangle as you suggested. and this should be fine, because the tracer finds points on the image [0..(size-1)] which then, we should add one unit to convert it to bounding rectangle.

So, It is fixed now, and thank you very much!

**Comment by dbeef** [comment]
Thank you too!
